@startuml Diagrama de Casos de Uso - InmoJaen

usecase (gestion usuarios) as Proc01
usecase (gestion anuncios) as Proc02
actor : admin: as Admin
Admin --> Proc01
Admin --> Proc02

usecase (gestionar su perfil de venta) as Proc03
usecase (publicar anuncios) as Proc04
usecase (gestionar anuncios publicados) as Proc05
usecase (enviar mensajes) as Proc06
usecase (aceptar reserva) as Proc07
usecase (rechazar reserva) as Proc08
usecase (finalizar reserva) as Proc09
usecase (gestionar su informacion) as Proc10
usecase (buscar anuncios) as Proc11
usecase (gestionar anuncios favoritos) as Proc12
usecase (enviar mensajes) as Proc13
usecase (solicitar reserva) as Proc14
actor : usuario: as Usuario
Usuario --> Proc03
Usuario --> Proc04
Usuario --> Proc05
Usuario --> Proc06
Usuario --> Proc07
Usuario --> Proc08
Usuario --> Proc09
Usuario --> Proc10
Usuario --> Proc11
Usuario --> Proc12
Usuario --> Proc13
Usuario --> Proc14

usecase ( registro / login ) as Proc15

Proc01 .. Proc15
Proc02 .. Proc15
Proc03 .. Proc15
Proc04 .. Proc15
Proc05 .. Proc15
Proc06 .. Proc15
Proc07 .. Proc15
Proc08 .. Proc15
Proc09 .. Proc15
Proc10 .. Proc15
Proc11 .. Proc15
Proc12 .. Proc15
Proc13 .. Proc15
Proc14 .. Proc15

@enduml