@startuml Diagrama de Casos de Uso - InmoJaen

usecase (gestion anuncios\n y usuarios) as Proc01
actor : admin: as Admin
Admin --> Proc01

usecase (gestionar su perfil de venta) as Proc02
usecase (gestionar anuncios publicados) as Proc03
actor : vendedor: as Vendedor
Vendedor --> Proc02
Vendedor --> Proc03

usecase (gestionar su informacion) as Proc04
usecase (buscar anuncios) as Proc05
usecase (gestionar anuncios favoritos) as Proc06
actor : cliente: as Cliente
Cliente --> Proc04
Cliente --> Proc05
Cliente --> Proc06

usecase ( registro / login ) as Proc07

Proc01 .. Proc07
Proc02 .. Proc07
Proc03 .. Proc07
Proc04 .. Proc07
Proc05 .. Proc07
Proc06 .. Proc07

@enduml